# Generated by Django 4.2 on 2023-05-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_choose_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullNames', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('current_destination', models.CharField(choices=[('Bamenda', 'Bamenda'), ('Douala', 'Douala'), ('Yaounde', 'Yaounde'), ('Buea', 'Buea')], max_length=50)),
                ('final_destination', models.CharField(choices=[('Bamenda', 'Bamenda'), ('Douala', 'Douala'), ('Yaounde', 'Yaounde'), ('Buea', 'Buea')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'CustomerRegistration',
                'verbose_name_plural': 'CustomerRegistration',
            },
        ),
    ]
