# Generated by Django 4.2 on 2023-06-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customerregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerregistration',
            name='no_of_sites',
            field=models.IntegerField(default=1),
        ),
    ]
