# Generated by Django 4.2 on 2023-06-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_slideshow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='town',
            field=models.CharField(default='Bamenda', max_length=50),
        ),
    ]
